config/routes.rb
Rails.application.routes.draw do
  resource :session
  get "signup" => "users#new"
  resources :users
  
  namespace :api do
    resources :meds
    resources :patients
    resources :protocols
  end

    get 'protocols' => 'protocols#index'
    get 'protocols/:id' => 'protocols#show'

    resources :protocols
    resources :patients

    resources :notes

    resources :labs

    resources :vital_signs

    resources :orders
    resources :meds
    root 'sessions#new'

  
  

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	has_many :vital_signs
	has_many :provider
end

app/models/lab.rb
class Lab < ActiveRecord::Base
	belongs_to :user
end

app/models/med.rb
class Med < ActiveRecord::Base
	belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :vital_signs
	has_many :consumers

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :kind, presence: true
  validates :email, presence: true,
  									format: /\A\S+@\S+\z/,
  									uniqueness: { case_sensitive: false }
  validates :pin, presence: true

  has_many :labs
  has_many :meds
  has_many :notes
  has_many :orders
  has_many :vital_signs

  def self.authenticate(email, password, pin)
  	user = User.find_by(email: email)
  	user && user.authenticate(password)
  end
end

app/models/vital_sign.rb
class VitalSign < ActiveRecord::Base
	belongs_to :user
	belongs_to :consumer
	belongs_to :provider
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
	before_action :require_signin
	def index
		@lab = Lab.all
	end

	def show
		@lab = Lab.find(params[:id])
	end

	def edit
		@lab = Lab.find(params[:id])
	end

	def update
		@lab = Lab.find(params[:id])
		@lab.update(lab_params)
		redirect_to @lab
	end

	def new
		@lab = Lab.new
	end

	def create
		@lab = Lab.new(lab_params)
		@lab.save
		redirect_to @lab
	end

	def destroy
		@lab = Lab.find(params[:id])
		@lab.destroy
		redirect_to labs_url
	end


	private

	def lab_params
		params.require(:lab).permit(:na, :cl, :bun, :k, :hco3, :cr, :wbc, :hgb, :htc, :plt, :glucose)
	end
end

app/controllers/vital_signs_controller.rb
class VitalSignsController < ApplicationController
	before_action :require_signin
	def index
		@vital_sign = VitalSign.all
	end

	def show
		@vital_sign = VitalSign.find(params[:id])
	end

	def edit
		@vital_sign = VitalSign.find(params[:id])
	end

	def update
		@vital_sign = VitalSign.find(params[:id])
		@vital_sign.update(vital_sign_params)
		redirect_to @vital_sign
	end

	def new
		@vital_sign = VitalSign.new
	end

	def create
		@vital_sign = VitalSign.new(vital_sign_params)
		@vital_sign.save
		redirect_to @vital_sign
	end

	def destroy
		@vital_sign = current_user.vital_sign.find(params[:id])
		@vital_sign.destroy
		redirect_to vital_signs_url
	end


	private

	def vital_sign_params
		params.require(:vital_sign).permit(:bpsys, :bpdia, :o2, :pulse, :resp, :temp,)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/protocol_helper.rb
module ProtocolHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vital_signs_helper.rb
module VitalSignsHelper
end

app/views/vital_signs/_form.html.erb
<ul class="form_ul">

<%= form_for(@vital_sign) do |f| %>
	<li>
		<%= f.label :bpsys %><br/>
		<%= f.text_field :bpsys, autofocus: true %>
	</li>
	<li>
		<%= f.label :bpdia %><br/>
		<%= f.text_field :bpdia %>
	</li>
	<li>
		<%= f.label :o2 %><br/>
		<%= f.text_field :o2 %>
	</li>
	<li>
		<%= f.label :pulse %><br/>
		<%= f.text_field :pulse %>
	</li>
	<li>
		<%= f.label :resp %><br/>
		<%= f.text_field :resp %>
	</li>
	<li>
		<%= f.label :temp %><br/>
		<%= f.text_field :temp %>
	</li>
	
	<li>
		<%= f.submit class: 'btn' %>
		<%= link_to "Cancel", vital_signs_path %>
	</li>
	
<% end %>
</ul>

app/views/vital_signs/edit.html.erb
<h1>Editing: <%= @vital_sign.pulse %></h1>
<div>
<%= link_to("vitals", vital_signs_path) %>
</div>
<%= render 'form' %>

app/views/vital_signs/index.html.erb
<div class="index">
<h3>Vitals list:</h3>
<nav>
<%= link_to("Add Vitals", new_vital_sign_path) %>
</nav>
	<ul>
	<% @vital_sign.each do |vital_sign| %>
		<h3><%= link_to(vital_sign.created_at, vital_sign_path(vital_sign)) %></h3>
		<li><%= vital_sign.pulse %> pulse</li>
		<li><%= vital_sign.bpsys %> BPS</li>
		<li><%= vital_sign.bpdia %> BPD</li>
		<li><%= vital_sign.o2 %> %  O2</li>
		<li><%= vital_sign.temp %> temp</li>
		<li><%= vital_sign.resp %> respirations</li>
	<% end %>
	</ul>
</div>

app/views/vital_signs/new.html.erb
<h3>create vitals list:</h3>
<div>
<%= link_to("all vitals", vital_signs_path) %>
</div>
<%= render 'form' %>

app/views/vital_signs/show.html.erb
<nav>
  <%= link_to("all vitals", vital_signs_path) %>
  <%= link_to("edit", edit_vital_sign_path(@vital_sign)) %>
  <%= link_to "delete", vital_sign_path(@vital_sign), method: :delete, data: { confirm: 'Are you sure?'} %>
</nav>

<div class="index">
  <h3>BP Systolic:</h3>
  <p>
    <%= @vital_sign.bpsys %>
  </p>
  <h3>BP Diastolic:</h3>
  <p>
    <%= @vital_sign.bpdia %>
  </p>
  <h3>O2:</h3>
  <p>
    <%= @vital_sign.o2 %>
  </p>
  <h3>Pulse:</h3>
  <p>
    <%= @vital_sign.pulse %>
  </p>
  <h3>Resp:</h3>
  <p>
    <%= @vital_sign.resp %>
  </p>
  <h3>Temp:</h3>
  <p>
    <%= @vital_sign.temp %>
  </p>
</div>