config/routes.rb
Rails.application.routes.draw do
  resource :session
  get "signup" => "users#new"
  resources :users
  
  namespace :api do
    resources :meds
    resources :patients
    resources :protocols
  end

    get 'protocols' => 'protocols#index'
    get 'protocols/:id' => 'protocols#show'

    resources :protocols
    resources :patients

    resources :notes

    resources :labs

    resources :vital_signs

    resources :orders
    resources :meds
    root 'sessions#new'

  
  

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	has_many :vital_signs
	has_many :provider
end

app/models/lab.rb
class Lab < ActiveRecord::Base
	belongs_to :user
end

app/models/med.rb
class Med < ActiveRecord::Base
	belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :vital_signs
	has_many :consumers

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :kind, presence: true
  validates :email, presence: true,
  									format: /\A\S+@\S+\z/,
  									uniqueness: { case_sensitive: false }
  validates :pin, presence: true

  has_many :labs
  has_many :meds
  has_many :notes
  has_many :orders
  has_many :vital_signs

  def self.authenticate(email, password, pin)
  	user = User.find_by(email: email)
  	user && user.authenticate(password)
  end
end

app/models/vital_sign.rb
class VitalSign < ActiveRecord::Base
	belongs_to :user
	belongs_to :consumer
	belongs_to :provider
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
	before_action :require_signin
	def index
		@lab = Lab.all
	end

	def show
		@lab = Lab.find(params[:id])
	end

	def edit
		@lab = Lab.find(params[:id])
	end

	def update
		@lab = Lab.find(params[:id])
		@lab.update(lab_params)
		redirect_to @lab
	end

	def new
		@lab = Lab.new
	end

	def create
		@lab = Lab.new(lab_params)
		@lab.save
		redirect_to @lab
	end

	def destroy
		@lab = Lab.find(params[:id])
		@lab.destroy
		redirect_to labs_url
	end


	private

	def lab_params
		params.require(:lab).permit(:na, :cl, :bun, :k, :hco3, :cr, :wbc, :hgb, :htc, :plt, :glucose)
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :require_signin

	def index
		@note = Note.all
	end

	def show
		@note = Note.find(params[:id])
	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		@note.update(note_params)
		redirect_to @note
	end

	def new
		@note = Note.new
	end

	def create
		@note = Note.new(note_params)
		@note.save
		redirect_to @note
	end

	def destroy
		@note = Note.find(params[:id])
		@note.destroy
		redirect_to notes_url
	end


	private

	def note_params
		params.require(:note).permit(:service, :subjective, :objective, :assessment,
		 :plan, :ordering_provider, :patient, :user_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/protocol_helper.rb
module ProtocolHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vital_signs_helper.rb
module VitalSignsHelper
end

app/views/notes/_form.html.erb
<ul class="form_ul">

<%= form_for(@note) do |f| %>
	<li>
		<%= f.label :service %><br/>
		<%= f.text_field :service, autofocus: true %>
	</li>
	<li>
		<%= f.label :subjective %><br/>
		<%= f.text_field :subjective %>
	</li>
	<li>
		<%= f.label :objective %><br/>
		<%= f.text_field :objective %>
	</li>
	<li>
		<%= f.label :assessment %><br/>
		<%= f.text_field :assessment %>
	</li>
	<li>
		<%= f.label :plan %><br/>
		<%= f.text_field :plan %>
	</li>
	<li>
		<%= f.label :ordering_provider %><br/>
		<%= f.text_field :ordering_provider %>
	</li>
	
	<li>
		<%= f.submit class: 'btn' %>
		<%= link_to "Cancel", notes_path %>
	</li>
	
<% end %>
</ul>

app/views/notes/edit.html.erb
<div class="index">
<h1>Editing: <%= @note.service %></h1>
<div>
<%= link_to("all notes", notes_path) %>
</div>
<%= render 'form' %>
</div>

app/views/notes/index.html.erb
<div class="index">
<h3>Notes list:</h3>
<div>
<%= link_to("Add Note", new_note_path) %>
</div>
	<ul>
	<% @note.each do |note|%>
		<h3><%= link_to(note.service, note_path(note)) %></h3>
		<li>
			<%= note.ordering_provider %> 
		</li>
	<% end %>
	</ul>
</div>

app/views/notes/new.html.erb
<div class="index">
<h3>create new note:</h3>
<div>
<%= link_to("all notes", notes_path) %>
</div>
<%= render 'form' %>
</div>

app/views/notes/show.html.erb
<div class="index">
<nav>
  <%= link_to("all notes", notes_path) %>
  <%= link_to("edit", edit_note_path(@note)) %>
  <%= link_to "delete", note_path(@note), method: :delete, data: { confirm: 'Are you sure?'} %>
</nav>

<article>
  <h3>Type:</h3>
  <p>
    <%= @note.service %>
  </p>
  <h3>Subjective:</h3>
  <p>
    <%= @note.subjective %>
  </p>
  <h3>Objective:</h3>
  <p>
    <%= @note.objective %>
  </p>
  <h3>Assessment:</h3>
  <p>
    <%= @note.assessment %>
  </p>
  <h3>Plan:</h3>
  <p>
    <%= @note.plan %>
  </p>
  <h3>Provider:</h3>
  <p>
    <%= @note.ordering_provider %>
  </p>
</article>
</div>