config/routes.rb
Rails.application.routes.draw do
  resource :session
  get "signup" => "users#new"
  resources :users
  
  namespace :api do
    resources :meds
    resources :patients
    resources :protocols
  end

    get 'protocols' => 'protocols#index'
    get 'protocols/:id' => 'protocols#show'

    resources :protocols
    resources :patients

    resources :notes

    resources :labs

    resources :vital_signs

    resources :orders
    resources :meds
    root 'sessions#new'

  
  

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	has_many :vital_signs
	has_many :provider
end

app/models/lab.rb
class Lab < ActiveRecord::Base
	belongs_to :user
end

app/models/med.rb
class Med < ActiveRecord::Base
	belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :vital_signs
	has_many :consumers

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :kind, presence: true
  validates :email, presence: true,
  									format: /\A\S+@\S+\z/,
  									uniqueness: { case_sensitive: false }
  validates :pin, presence: true

  has_many :labs
  has_many :meds
  has_many :notes
  has_many :orders
  has_many :vital_signs

  def self.authenticate(email, password, pin)
  	user = User.find_by(email: email)
  	user && user.authenticate(password)
  end
end

app/models/vital_sign.rb
class VitalSign < ActiveRecord::Base
	belongs_to :user
	belongs_to :consumer
	belongs_to :provider
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
	before_action :require_signin
	def index
		@lab = Lab.all
	end

	def show
		@lab = Lab.find(params[:id])
	end

	def edit
		@lab = Lab.find(params[:id])
	end

	def update
		@lab = Lab.find(params[:id])
		@lab.update(lab_params)
		redirect_to @lab
	end

	def new
		@lab = Lab.new
	end

	def create
		@lab = Lab.new(lab_params)
		@lab.save
		redirect_to @lab
	end

	def destroy
		@lab = Lab.find(params[:id])
		@lab.destroy
		redirect_to labs_url
	end


	private

	def lab_params
		params.require(:lab).permit(:na, :cl, :bun, :k, :hco3, :cr, :wbc, :hgb, :htc, :plt, :glucose)
	end
end

app/controllers/meds_controller.rb
class MedsController < ApplicationController
	before_action :require_signin

	def index
		@meds = Med.all
	end

	def show
		@med = Med.find(params[:id])
	end

	def edit
		@med = Med.find(params[:id])
	end

	def update
		@med = Med.find(params[:id])
		@med.update(med_params)
		redirect_to @med
	end

	def new
		@med = Med.new
	end

	def create
		@med = Med.new(med_params)
		@med.save
		redirect_to @med
	end

	def destroy
		@med = Med.find(params[:id])
		@med.destroy
		redirect_to meds_url
	end


	private

	def med_params
		params.require(:med).permit(:name, :dose, :dose_timing, :ordering_provider, :route, :start_date, :end_date, :user_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/protocol_helper.rb
module ProtocolHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vital_signs_helper.rb
module VitalSignsHelper
end

app/views/labs/_form.html.erb
<ul class="form_ul">

<%= form_for(@lab) do |f| %>
	<li>
		<%= f.label :na %><br/>
		<%= f.text_field :na, autofocus: true %>
	</li>
	<li>
		<%= f.label :cl %><br/>
		<%= f.text_field :cl %>
	</li>
	<li>
		<%= f.label :bun %><br/>
		<%= f.text_field :bun %>
	</li>
	<li>
		<%= f.label :k %><br/>
		<%= f.text_field :k %>
	</li>
	<li>
		<%= f.label :hco3 %><br/>
		<%= f.text_field :hco3 %>
	</li>
	<li>
		<%= f.label :wbc %><br/>
		<%= f.text_field :wbc %>
	</li>
	<li>
		<%= f.label :hgb %><br/>
		<%= f.text_field :hgb %>
	</li>
	<li>
		<%= f.label :htc %><br/>
		<%= f.text_field :htc %>
	</li>
	<li>
		<%= f.label :plt %><br/>
		<%= f.text_field :plt %>
	</li>
	<li>
		<%= f.label :glucose %><br/>
		<%= f.text_field :glucose %>
	</li>
	
	<li>
		<%= f.submit class: 'btn' %>
		<%= link_to "Cancel", labs_path %>
	</li>
	
<% end %>
</ul>

app/views/labs/edit.html.erb
<div class="index">
<h1>Editing: <%= @lab.glucose %></h1>
<div>
<%= link_to("all labs", labs_path) %>
</div>
<%= render 'form' %>
</div>

app/views/labs/index.html.erb
<div class="index">
<h3>Labs list:</h3>
<div>
<%= link_to("Add Labs", new_lab_path) %>
</div>
	<ul>
	<% @lab.each do |lab|%>
		<h3><%= link_to(lab.na, lab_path(lab)) %></h3>
		<li>
			<%= lab.bun %> 
		</li>
	<% end %>
	</ul>
</div>

app/views/labs/new.html.erb
<div class="index">
<h3>create new lab:</h3>
<div>
<%= link_to("all labs", labs_path) %>
</div>
<%= render 'form' %>
</div>

app/views/labs/show.html.erb
<div class="index">
<nav>
  <%= link_to("all labs", labs_path) %>
  <%= link_to("edit", edit_lab_path(@lab)) %>
  <%= link_to "delete", lab_path(@lab), method: :delete, data: { confirm: 'Are you sure?'} %>
</nav>

  <h3>Sodium:</h3>
  <p>
    <%= @lab.na %>
  </p>
  <h3>Cloride:</h3>
  <p>
    <%= @lab.cl %>
  </p>
  <h3>BUN:</h3>
  <p>
    <%= @lab.bun %>
  </p>
  <h3>Potassium:</h3>
  <p>
    <%= @lab.k %>
  </p>
  <h3>HCO3:</h3>
  <p>
    <%= @lab.hco3 %>
  </p>
  <h3>Cr:</h3>
  <p>
    <%= @lab.cr %>
  </p>
   <h3>WBC:</h3>
  <p>
    <%= @lab.wbc %>
  </p>
  <h3>HGB:</h3>
  <p>
    <%= @lab.hgb %>
  </p>
  <h3>Hematocrit:</h3>
  <p>
    <%= @lab.htc %>
  </p>
  <h3>Platelet:</h3>
  <p>
    <%= @lab.plt %>
  </p>
  <h3>Glucose:</h3>
  <p>
    <%= @lab.glucose %>
  </p>
</div>