config/routes.rb
Rails.application.routes.draw do
  resource :session
  get "signup" => "users#new"
  resources :users
  
  namespace :api do
    resources :meds
    resources :patients
    resources :protocols
  end

    get 'protocols' => 'protocols#index'
    get 'protocols/:id' => 'protocols#show'

    resources :protocols
    resources :patients

    resources :notes

    resources :labs

    resources :vital_signs

    resources :orders
    resources :meds
    root 'sessions#new'

  
  

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	has_many :vital_signs
	has_many :provider
end

app/models/lab.rb
class Lab < ActiveRecord::Base
	belongs_to :user
end

app/models/med.rb
class Med < ActiveRecord::Base
	belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :vital_signs
	has_many :consumers

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :kind, presence: true
  validates :email, presence: true,
  									format: /\A\S+@\S+\z/,
  									uniqueness: { case_sensitive: false }
  validates :pin, presence: true

  has_many :labs
  has_many :meds
  has_many :notes
  has_many :orders
  has_many :vital_signs

  def self.authenticate(email, password, pin)
  	user = User.find_by(email: email)
  	user && user.authenticate(password)
  end
end

app/models/vital_sign.rb
class VitalSign < ActiveRecord::Base
	belongs_to :user
	belongs_to :consumer
	belongs_to :provider
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/protocol_helper.rb
module ProtocolHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag 'favicon.png' %>
	<link href='http://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
  <title>(evr)</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

		
		<div class="topbar">
			<div class="toptile user">
			  <% if current_user %>
			  	<%= link_to current_user.email, current_user %> <br>
			  	<%= link_to "Sign Out", session_path, method: :delete %>
			  <% else %>
			  	<%= link_to "Sign Up", signup_path %>
					<%= link_to "Sign In", new_session_path %>
				<% end %>
			</div>
			<div class="toptile">
				<%= link_to("Notes list", notes_path) %>
			  <%= link_to("Add Note", new_note_path) %>
			</div>
			<div class="toptile">
				<%= link_to("Labs list", labs_path) %>
			  <%= link_to("Add Lab", new_lab_path) %>
			</div>
			<div class="toptile">
				<%= link_to("Vitals list", vital_signs_path) %>
			  <%= link_to("Add Vitals", new_vital_sign_path) %>
			</div>
			<div class="toptile">
				<%= link_to("Meds list", meds_path) %>
			  <%= link_to("Add Med", new_med_path) %>   
			</div>
		</div>
		

		

		<div class="rtbar">
			<div class="rttile">
				<%= link_to "Sign Out", session_path, method: :delete %>
				<%= link_to "Protocols", protocols_path %>
			</div>
			<div class="rttile">
				<%= link_to("Orders list", orders_path) %>
			  <%= link_to("Add Order", new_order_path) %>
			</div>
			<div class="rttile">
				<%= link_to("Pt's list", patients_path) %> 
			  <%= link_to("Add Pt", new_patient_path) %>
			</div>
		</div>

		<div class="content">
			<%= yield %>
			<% if notice %>
  			<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
  			<p class="alert alert-danger"><%= alert %></p>
			<% end %>
		</div>

	</body>
</html>